### PR TITLE
Updated pkg ver, changed source to official source and patched opencv issue

### PR DESCRIPTION
**Pull request by acxz**

### CODE REVIEW

**Comment by bionade24** [comment]
Thanks, updated both packages! Are there any OpenCV4 compatible ROS melodic packages at the moment or will melodic stuck with opencv3?

**Comment by acxz** [comment]
Just saw, thanks!
There are some packages that actually do work with opencv4 (can't name them off the top of my head), but others explicitly require opencv3. For some reason this was causing an issue for this package specifically that I had to patch to explicitly use opencv3 when it is technically not required (shouldn't be at least). (Related issue: https://github.com/ros-perception/image_pipeline/issues/420).

**Comment by acxz** [comment]
Went ahead and installed the entire `ros-melodic-perception` package on the AUR to check and it builds completely now. (man pcl takes such a long time)
I have traced the next error down to the `ignition-transport` package and have submitted a request to orphan it since the maintainer has not responded to any comments or direct emails. Right now that is the current bottleneck.

**Comment by bionade24** [comment]
If you get ownership, please mark me as co-maintainer, then I'll mirror the packages.

**Comment by acxz** [comment]
Sure, but they are not ros packages. Gazebo requires them. I do not believe they would fit in this organization.

**Comment by bionade24** [comment]
Ok, I'll already wondred why I'm owning it, because on the official builds it's has a ros version prefix.

**Comment by acxz** [comment]
None of the official builds for ignition packages have the ros version prefix nor are they in the ros wiki.
https://bitbucket.org/ignitionrobotics/

**Pull request merged**
